name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ sercrets.SSH_HOST }}
          username: ${{ sercrets.SSH_USER }}
          key: ${{ sercrets.SSH_KEY }}
          script: |
            cd gis-cdn
            cd ..
            docker compose build
            docker compose up -d
                    